# Generated by Django 2.0.7 on 2018-08-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default=None, max_length=140, unique=True),
            preserve_default=False,
        ),
    ]
