# Generated by Django 2.0.7 on 2018-08-02 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0002_thread_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thread',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
    ]
