# Generated by Django 2.0.7 on 2018-08-02 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0006_auto_20180802_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thred',
            new_name='thread',
        ),
    ]
