# Generated by Django 2.0.7 on 2018-08-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0007_auto_20180802_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
