# Generated by Django 2.0.7 on 2018-08-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0009_auto_20180803_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='subject',
            field=models.CharField(default="Hello", max_length=150),
            preserve_default=False,
        ),
    ]
