# Generated by Django 2.0.7 on 2018-08-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0010_thread_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='subject',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
