# Generated by Django 2.0.7 on 2018-07-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0002_auto_20180731_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtime',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventtime',
            name='duration',
            field=models.DurationField(blank=True, default=0),
        ),
    ]
