# Generated by Django 2.0.7 on 2018-08-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='musician',
        ),
        migrations.AddField(
            model_name='band',
            name='musician',
            field=models.ManyToManyField(related_name='bands', to='musicapp.Musician'),
        ),
    ]
