# Generated by Django 2.0.7 on 2018-08-02 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_auto_20180802_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='musician',
        ),
    ]
