# Generated by Django 2.0.7 on 2018-07-31 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('website', models.URLField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('prefix', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('release_date', models.DateField()),
                ('cover_image', models.URLField()),
                ('review', models.TextField()),
                ('asin', models.CharField(max_length=50)),
                ('directors', models.ManyToManyField(to='moviesapp.Director', verbose_name='Director')),
                ('genre', models.ManyToManyField(to='moviesapp.Genre', verbose_name='Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('prefix', models.CharField(max_length=50)),
                ('website', models.URLField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviesapp.Studio', verbose_name='Studio'),
        ),
    ]
