# Generated by Django 2.0.7 on 2018-08-01 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0002_auto_20180731_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(related_name='moviedirector', to='moviesapp.Director', verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='moviegenre', to='moviesapp.Genre', verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moviestudio', to='moviesapp.Studio', verbose_name='Studio'),
        ),
    ]
